### ISSUE TITLE
Help decide which libraries and tools to use

### ISSUE THREAD

**Issue by andytudhope** [andytudhope/APerspectiveOnTechnology#1]
Hi all,

I would love to get this repo up and running as an actual 3-D, web-accessible site. If anyone hs the skills required to achieve this, sign up!

**Comment by status-open-bounty** [comment]
Current balance: 0.1 ETH
Contract address: [0xa426f9d2462f29eb4252ed48df4b95f1f10cf62a](https://ropsten.etherscan.io/address/0xa426f9d2462f29eb4252ed48df4b95f1f10cf62a)
![QR Code](https://testing.openbounty.status.im/qr/andytudhope/APerspectiveOnTechnology/bounty/1/7620a4c5c169798f0da44682761a38b10870e00df5e3cf41e032423b4c99787c/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://testing.openbounty.status.im](https://testing.openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.

**Comment by AndreasS2501** [comment]
Hi Andy,

Thanks for opening this up!I was looking into different possibilities and found three.js as a clj lib so I got this mini template running:
https://bitbucket.org/Andreas2501/cubes

there are good examples available:
https://threejs.org/examples/#webgl_interactive_cubes_gpu

But I Think wokring with clojure helps avoiding the js madness ;)

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x9d8f443d1f039d9ec0200f9e53861f4da8006c3c](https://etherscan.io/address/0x9d8f443d1f039d9ec0200f9e53861f4da8006c3c)
![QR Code](https://openbounty.status.im/qr/andytudhope/APerspectiveOnTechnology/bounty/1/7228cf57b2cb76a3a2138d7b2951bca89dbc77db67f7d2e75764dc6fab1b2b28/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im)
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.
