### ISSUE TITLE
Test Issue for new GH permissions

### ISSUE THREAD

**Issue by andytudhope** [andytudhope/APerspectiveOnTechnology#2]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xb025c042768bfc2308f86c5479d098633e2a0a4c7af1ad7b4bdeed256e4684ad](https://etherscan.io/tx/0xb025c042768bfc2308f86c5479d098633e2a0a4c7af1ad7b4bdeed256e4684ad)

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x38d55b467776341ab5920ff3e56af706295d107b](https://ropsten.etherscan.io/address/0x38d55b467776341ab5920ff3e56af706295d107b)
![QR Code](https://openbounty.status.im:444/qr/andytudhope/APerspectiveOnTechnology/bounty/2/621047fbfda4c08523528812cbaca906813d309dae5ac4da598f722436583f7c/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
